### ISSUE TITLE
Slab memory leak on Lenovo Tab K10 

### ISSUE THREAD

**Issue by C0rn3j** [AndyCGYan/lineage_build_unified#55]
Within 2 weeks, the poor tablet leaks its entire memory and freezes.

I have had this issue for a while, upgrading the ROM did not previously help.

Will try updating to the latest October build soon.

Version
```
[ro.lineage.display.version]: [20-20230815-UNOFFICIAL-arm64_bgN]
```

Early meminfo
```yaml
MemTotal:        3963596 kB
MemFree:           65124 kB
MemAvailable:    1502348 kB <--------
Buffers:           50040 kB
Cached:          1450256 kB
SwapCached:        15916 kB
Active:          1279268 kB
Inactive:         848176 kB
Active(anon):     314608 kB
Inactive(anon):   328648 kB
Active(file):     964660 kB
Inactive(file):   519528 kB
Unevictable:        3512 kB
Mlocked:            3512 kB
SwapTotal:       2179972 kB
SwapFree:        1960836 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:        615636 kB
Mapped:           509624 kB
Shmem:             13548 kB
KReclaimable:      72204 kB
Slab:            1362624 kB <--------
SReclaimable:      72204 kB
SUnreclaim:      1290420 kB <--------
KernelStack:       26416 kB
PageTables:        46316 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4161768 kB
Committed_AS:   44865524 kB
VmallocTotal:   263061440 kB
VmallocUsed:       62964 kB
VmallocChunk:          0 kB
Percpu:             7616 kB
CmaTotal:         344064 kB
CmaFree:           13728 kB
```

Late meminfo
```yaml
MemTotal:        3963596 kB
MemFree:          164524 kB
MemAvailable:     438764 kB <--------
Buffers:            4324 kB
Cached:           352532 kB
SwapCached:         7044 kB
Active:           398228 kB
Inactive:         384668 kB
Active(anon):     246720 kB
Inactive(anon):   202312 kB
Active(file):     151508 kB
Inactive(file):   182356 kB
Unevictable:        3672 kB
Mlocked:            3672 kB
SwapTotal:       2179972 kB
SwapFree:        1677188 kB
Dirty:               124 kB
Writeback:             0 kB
AnonPages:        426776 kB
Mapped:           245044 kB
Shmem:             19912 kB
KReclaimable:      46888 kB
Slab:            2502976 kB <--------
SReclaimable:      46888 kB
SUnreclaim:      2456088 kB <--------
KernelStack:       27952 kB
PageTables:        47484 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4161768 kB
Committed_AS:   45641476 kB
VmallocTotal:   263061440 kB
VmallocUsed:       64524 kB
VmallocChunk:          0 kB
Percpu:             7616 kB
CmaTotal:         344064 kB
CmaFree:           79860 kB
```

---

If this is not the place to report this, where would be? 

https://sourceforge.net/projects/andyyan-gsi/support is not filled out.

---

Does Android not have `/proc/slabinfo` for some reason? I can't access it on my device.
